import { NextResponse } from "next/server";
import { saveFile } from "@/lib/storage";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/apiAuth";
import { generateMarathiLetter } from "@/lib/letterGenerator";

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { user, response } = await requireRole(["PA", "COLLECTOR", "ADMIN"]);
  if (!user) return response;

  try {
    const { id } = await params;
    const body = await req.json().catch(() => ({}));

    // Requires an explicit confirmation flag from the client (see
    // VisitorTable.tsx - a confirm dialog asks the staff member to affirm
    // they've reviewed the case before it's generated under the Collector's
    // signature). This closes the gap where a letter could be issued with a
    // single accidental click and no human-in-the-loop check.
    if (!body.confirmed) {
      return NextResponse.json(
        { error: "Letter generation requires explicit confirmation that the case has been reviewed." },
        { status: 400 }
      );
    }

    const visitor = await prisma.visitor.findUnique({
      where: { id },
      include: { assignedDepartment: true },
    });

    if (!visitor) return NextResponse.json({ error: "Not found" }, { status: 404 });
    if (!visitor.assignedDepartment) {
      return NextResponse.json({ error: "Assign a department before generating the letter" }, { status: 400 });
    }

    const jaKrCounter = await prisma.auditLog.count({ where: { action: "LETTER_GENERATED" } });
    const jaKr = `जिका/जालना/तक्रार/${new Date().getFullYear()}/${String(jaKrCounter + 1).padStart(4, "0")}`;

    const today = new Date();
    const refDate = `${String(today.getDate()).padStart(2, "0")}/${String(
      today.getMonth() + 1
    ).padStart(2, "0")}/${today.getFullYear()}`;

    const pdfBytes = await generateMarathiLetter({
      tokenNo: visitor.tokenNo,
      refDate,
      departmentNameMarathi: visitor.assignedDepartment.nameMarathi,
      visitorName: visitor.name,
      visitorAddress: `${visitor.address}, ${visitor.village}, ता. ${visitor.taluka}, जि. ${visitor.district}`,
      subject: visitor.subject,
      aiSummary: visitor.aiSummary || undefined,
      jaKr,
    });

    const saved = await saveFile(
      `letters/${visitor.tokenNo.replace(/\//g, "-")}.docx`,
      pdfBytes,
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    );

    await prisma.visitor.update({
      where: { id },
      data: {
        letterGenerated: true,
        letterUrl: saved.url,
        letterGeneratedAt: new Date(),
        letterConfirmedById: user.id,
      },
    });

    // Explicit, permanent record of who confirmed this letter went out under
    // the Collector's name - addresses "auto-signed with no accountability".
    await prisma.auditLog.create({
      data: {
        visitorId: id,
        userId: user.id,
        action: "LETTER_GENERATED",
        details: `${jaKr} - confirmed and generated by ${user.name} (${user.role})`,
      },
    });

    return NextResponse.json({ success: true, letterUrl: saved.url });
  } catch (err: any) {
    console.error("Letter generation failed:", err);
    return NextResponse.json(
      { error: err.message || "Letter generation failed. Please try again." },
      { status: 500 }
    );
  }
}
